<a href="https://colab.research.google.com/github/anilvce/mathslab/blob/main/Exp_5_EigenVector_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import linalg

m = 4
n = 4

A = np.random.standard_exponential(size=(m,n))

A=np.array([[1,2],[2,3]])
print(A)
lam, V = linalg.eig(A)

print(lam)
print(V)

[[1 2]
 [2 3]]
[-0.23606798+0.j  4.23606798+0.j]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [ ]:
ainv=linalg.inv(A)
lam1,V1=linalg.eig(ainv)
print(lam1)
print(V1)
if (lam==lam1).all():
  print(" equal")
else:
  print("not Equal")

[-4.23606798+0.j  0.23606798+0.j]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
not Equal


### EigenVector Decomposition
###### A (nonzero) vector v of dimension N is an eigenvector of a square N × N matrix A if it satisfies a linear equation of the form

###### Av  = Lambda*v

###### for some scalar λ. Then λ is called the eigenvalue corresponding to v. Geometrically speaking, the eigenvectors of A are the vectors that A merely elongates or shrinks, and the amount that they elongate/shrink by is the eigenvalue. The above equation is called the eigenvalue equation or the eigenvalue problem.

In [ ]:
print(A.dot(V))
print(lam * V )

[[ 0.20081142 -2.22703273]
 [-0.12410828 -3.60341465]]
[[ 0.20081142-0.j -2.22703273+0.j]
 [-0.12410828+0.j -3.60341465+0.j]]


In [ ]:
print(linalg.norm(A.dot(V) - lam*V))

7.260351408704585e-16


In [ ]:
# A @ V = lambda * V = V * Lambda 
# A = V*lambda @ V-inv

m=n=2
lambdaMatrix = np.zeros((m, n) , dtype=complex)
lambdaInvMatrix = np.zeros((m, n), dtype=complex)
for i in range(min(m, n)):
    lambdaMatrix[i, i] = lam[i]
    lambdaInvMatrix[i, i] = 1/lam[i]

Vinv = linalg.inv(V)
print( (V.dot(lambdaMatrix)).dot(Vinv) )

print(A)

[[1.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]]
[[1 2]
 [2 3]]


In [ ]:
# A = V*lambda @ V-inv
# Ainv = V * (Lambdainv) @ (V-inv)

Vinv = linalg.inv(V)
#print(Vinv)
Ainv = V.dot(lambdaInvMatrix).dot(Vinv)
print(Ainv)
Ainvd = linalg.inv(A)
print(Ainvd)

print(linalg.norm(Ainv - Ainvd))

[[-3.+0.j  2.+0.j]
 [ 2.+0.j -1.+0.j]]
[[-3.  2.]
 [ 2. -1.]]
1.9641850382783467e-15


In [ ]:
# det(A) = multipy lambda values

print("Det:\n{}".format(linalg.det(A)))
print(lam)
print(lam[0]*lam[1])
print("lambda Cumulative product:\n{}".format(lam.cumprod()) )

Det:
-1.0
[-0.23606798+0.j  4.23606798+0.j]
(-1.0000000000000004+0j)
lambda Cumulative product:
[-0.23606798+0.j -1.        +0.j]


In [ ]:
# Trace(A) = sum lambda values
print("Trace:\n{}".format(np.trace(A)))
print("lambda Cumulative sum:\n{}".format(lam.cumsum()) )

Trace:
4
lambda Cumulative sum:
[-0.23606798+0.j  4.        +0.j]


In [ ]:
D = np.array( [(1,1), (0,1)] )
print(D)
lamn, Vn = linalg.eig(D)
print(lamn)
print(Vn)
print(linalg.norm(D.dot(Vn) - lamn*Vn))

[[1 1]
 [0 1]]
[1.+0.j 1.+0.j]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]
2.220446049250313e-16


In [ ]:
arr=np.array([[1,1],[2,2]])
print(linalg.norm(arr))
import math
print(math.sqrt(10))

3.1622776601683795
3.1622776601683795


In [ ]:
#Exercises
#Compute eigenvectors and eigen values for any random (3,3) matrix
#compute inverse for any random matrix using Eigen factorization and verify with inv() & pinv() methods.
#Compute and compare eigenvectors and eigen values for any 
random (3,3) matrix and its inverse matrix - verify the results
#Compute and compare eignevectors and eigne values for any real
 symmetric matrx and verify the results - eigen values are real 
#Compute eignevectors and eigne values for any real symmetric matrx - 
check eigen vectors are othogonal
#verify matrix is not invertible if any one of its eigen value is zero.

#Positive Definite Matrix - 1) symmetric, 2) all eigenvalues are positive, 3) all the subdeterminants are also positive
#Read - https://towardsdatascience.com/decomposing-eigendecomposition-f68f48470830

SyntaxError: ignored

In [ ]:
import numpy as np
import scipy
import scipy.linalg as lin
A=np.random.standard_exponential(size=(3,3))
lam,V=lin.eig(A)
print('A:\n', A)
b=lam
c=V
print('\n lam=',b)
print('\n V=',c)
Ainv=lin.inv(A)
lam1,V1=lin.eig(Ainv)
print('\nAinv:\n',Ainv)
d=lam1
e=V1
print('\n lam1=',d)
print('\n v1=',e)
print('\n v1 inverse', lin.inv(e))

print("b.all=",b.all())
print("c.all=",c.all())
if(b==d).all():
  print('\nverfied')
else:
  print('\nnot verified')
if(e==c).all():
  print('\nverfied')
else:
  print('\nnot verified')


In [ ]:
arr=[]
arr.append(10)
arr.append(20)
a1=np.array()


In [ ]:
import numpy as np
import scipy
import scipy.linalg as lin

A=np.array([[12, -51, 4], [6,167,-68], [-4,24,-41]])
Q=np.array([[6/7,-69/175,-58/175], [3/7, 158/175,6/175], [-2/7, 6/35, -33/35]])
Qinv=lin.inv(Q)
R=Qinv.dot(A)
print(R)
print(Q.dot(R))