<a href="https://colab.research.google.com/github/anilvce/mathslab/blob/main/Exp_4_MatrixAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import scipy.linalg as spylinalg

a = np.random.normal(5, 1, size=(4,4))
#a=np.array([1,2])
ainv = spylinalg.inv(a)
print(ainv)

[[ 2.24253843 -0.1558048   1.04788248 -2.904085  ]
 [-1.80920058 -0.83056545 -1.22512089  3.71392584]
 [ 0.21438937  1.12110024 -1.26053965 -0.00458271]
 [-0.22279174 -0.26515082  1.91690798 -1.34455515]]


In [ ]:
print(a.dot(ainv))

[[ 1.00000000e+00  3.66565710e-16  1.33749521e-15  1.50286007e-15]
 [-6.64797503e-15  1.00000000e+00  2.76872386e-15  1.11957727e-15]
 [-4.09447677e-15  2.31806067e-16  1.00000000e+00  6.11841148e-15]
 [-4.95553734e-15  1.40757349e-15  3.29585669e-15  1.00000000e+00]]


In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
print(spylinalg.det(a))


-13.009684848947138


In [ ]:
spylinalg.norm(a)
help(spylinalg.norm)

Help on function norm in module scipy.linalg.misc:

norm(a, ord=None, axis=None, keepdims=False, check_finite=True)
    Matrix or vector norm.
    
    This function is able to return one of seven different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    a : (M,) or (M, N) array_like
        Input array.  If `axis` is None, `a` must be 1-D or 2-D.
    ord : {non-zero int, inf, -inf, 'fro'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object
    axis : {int, 2-tuple of ints, None}, optional
        If `axis` is an integer, it specifies the axis of `a` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these matrices
        are computed.  If `axis` is None then either a vector norm (when `a`
        is 1-D) or a 

In [ ]:
arect = np.random.normal(5, 1, size=(4,3))
print(spylinalg.inv(arect))

ValueError: ignored

In [ ]:
arectinv = spylinalg.pinv(arect)
print(arectinv)
print(arect.dot(arectinv))

[[ 0.26611937 -0.2344416  -0.66507178  0.52241548]
 [-0.25602456 -0.02085655  0.47412851 -0.02156166]
 [ 0.02226595  0.29939029  0.26924692 -0.45745819]]
[[ 0.63273488  0.42194265 -0.17263401  0.15666317]
 [ 0.42194265  0.51523956  0.19833534 -0.1799868 ]
 [-0.17263401  0.19833534  0.91885289  0.07363997]
 [ 0.15666317 -0.1799868   0.07363997  0.93317267]]


In [ ]:
a = np.random.normal(5, 1, size=(4,4))
print(a)
print(np.trace(a))

[[5.28084561 5.16122572 5.60005218 5.70043949]
 [5.99090008 5.79489638 4.50988412 5.58252978]
 [4.60874129 3.8412757  4.47377709 4.71468718]
 [5.30814038 5.66470582 4.45023101 5.18429288]]
20.733811951743927


In [ ]:
#Exercises


In [ ]:
# A Aiv = Ainv A =1
# (A.inv).inv = A
# (AB).inv = B.inv A.inv
# (A.T).inv = (A.inv).T
#(k * A.inv) = 1/k * A.inv  ; k - scalar
# pick some properties related to determinant, Trace & Rank