<a href="https://colab.research.google.com/github/anilvce/mathslab/blob/main/Exp_7_Solve_LinearEquations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### solve system of linear equations:
x+2y = 5 3x+4y = 7 Ax = b

x = Ainv.dot(b)

In [ ]:
#x+2y = 5 3x+4y = 7 Ax = b
#x = Ainv.dot(b)
import numpy as np
from scipy import linalg

A= np.array([[1,2], [3,4]])
b= np.array([5,7])
x= linalg.inv(A).dot(b)
print(x)
print(A.dot(x))

[-3.  4.]
[5. 7.]


In [ ]:
linalg.solve(A, b)

array([-3.,  4.])

In [ ]:
m = 4; n=2
A = np.random.randint(100, size=(m,n))
b = np.random.randint(100, size=(m,1))
print("A=\n{}".format(A))
print("b=\n{}".format(b))

A=
[[92 82]
 [ 1 89]
 [47 20]
 [93 88]]
b=
[[93]
 [23]
 [37]
 [79]]


In [ ]:
#linalg.solve(A, b) - does not work
Ainv = linalg.pinv(A)
x = Ainv.dot(b)
print(x)
print(A.dot(x) - b)

[[0.69933579]
 [0.24776121]]
[[-8.34468841]
 [-0.24991642]
 [ 0.82400614]
 [ 7.84121464]]


In [ ]:
#Minimizing |Ax-b|
x, res, rnk, s = linalg.lstsq(A, b)
print(x)
print(A.dot(x) - b)

[[0.69933579]
 [0.24776121]]
[[-8.34468841]
 [-0.24991642]
 [ 0.82400614]
 [ 7.84121464]]
